### PR TITLE
a few quick visual changes [#1]

### PR DESCRIPTION
**Pull request by hmig**
Updates per issue [#1].

### CODE REVIEW

**Comment by micahgodbolt** [comment]
I like it! Very modern flat design. Winner!

**Comment by hmig** [comment]
Awesome! :dancer:

**Comment by klamping** [comment]
Oh yeah, I like that look better. The gray fits well. Thanks!

**Comment by hmig** [comment]
Yay! Glad you like it! Now, I can focus on setting up my regression
testing. LOL. :D

**Pull request merged**
